menu:
  - name: 'accueil'
    url: '/accueil'
  - name: 'publications'
    url: '/publications'
  - name: 'webographie'
    url: '/webographie'
  - name: 'membres'
    url: '/membres'
  - name: 'about'
    url: '/about'

accueil: []

publications: []

webographie: []

membres: []

about: []
